name: FeelGoodMG
favicon: null
layout_spectrum: 0.90727
typography_spectrum: 0.30209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002f73'
    - '#acceeb'
    - '#000080'
    - '#ffffff'
    - '#728cb3'
  brandStrength: 0.5625
  lightness: 0.31621128786355257
  saturation: 0.21508705662563443
  rhythmicContrast: 0.11037463042885065
purpose: []
